# Generated by Django 4.2.3 on 2023-07-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_plan', models.CharField(choices=[('Daily_plan', 'Daily Plan'), ('Thought', 'Thought'), ('Feeling', 'Feeling'), ('Workout', 'Workout')], default='Daily_plan', max_length=100)),
                ('Thought', models.TextField()),
                ('Feeling', models.CharField(choices=[('Daily_plan', 'Daily Plan'), ('Thought', 'Thought'), ('Feeling', 'Feeling'), ('Workout', 'Workout')], default='Feeling', max_length=100)),
                ('Workout', models.CharField(choices=[('Daily_plan', 'Daily Plan'), ('Thought', 'Thought'), ('Feeling', 'Feeling'), ('Workout', 'Workout')], default='Workout', max_length=100)),
            ],
        ),
    ]
