# Generated by Django 4.2.3 on 2023-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('Daily_plan', 'Daily Plan'), ('Thought', 'Thought'), ('Feeling', 'Feeling'), ('Workout', 'Workout')], default='Choice', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='Daily_plan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Feeling',
            field=models.CharField(choices=[('Bad', 'Bad'), ('Good', 'Good'), ('Stress', 'Stress'), ('Angry', 'Angry'), ('Happy', 'Happy')], default='Choice', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Workout',
            field=models.CharField(max_length=100),
        ),
    ]
