# Generated by Django 4.2.3 on 2023-07-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_title_alter_post_daily_plan_alter_post_feeling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_description', models.TextField()),
                ('plan_date', models.DateField()),
                ('plan_time', models.TimeField()),
            ],
        ),
    ]
