# Generated by Django 4.2.3 on 2023-07-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_dailyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
