# Generated by Django 4.2.3 on 2023-07-28 09:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_dailyplan_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.upload_location, width_field='width_field'),
        ),
    ]
