# Generated by Django 4.2.3 on 2023-07-28 09:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_dailyplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
    ]
