# Generated by Django 4.2.3 on 2023-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Thought',
            new_name='Create_Post',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('Daily_plan', 'Daily Plan'), ('Create_post', 'Create_post'), ('Feeling', 'Feeling'), ('Workout', 'Workout')], default='Choice', max_length=50),
        ),
    ]
