# Generated by Django 4.2.3 on 2023-07-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_thought_post_create_post_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50)),
                ('post_description', models.TextField()),
                ('post_date', models.DateField()),
                ('post_time', models.TimeField()),
                ('Feeling', models.CharField(choices=[('Bad', 'Bad'), ('Good', 'Good'), ('Stress', 'Stress'), ('Angry', 'Angry'), ('Happy', 'Happy')], default='Choice', max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('post_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
