# Generated by Django 4.2.3 on 2023-07-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_post_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='post_location',
        ),
    ]
